// src/pages/api/contact.ts
// Handles general contact form submissions.
// DO NOT edit this file per client — update src/lib/email.config.ts instead.

import type { APIRoute } from 'astro';
import { Resend } from 'resend';
import { EMAIL_CONFIG } from '~/lib/email.config';
import { sendWithAlert, notifySubmission, fieldsFromFormData } from '~/lib/form-alert';

const resend = new Resend(import.meta.env.RESEND_API_KEY);
// Astro reads env via import.meta.env, so pass the Slack URL explicitly.
// Slack destination. FORM_SLACK_WEBHOOK is this client's own channel and takes
// precedence for BOTH submissions and failures; FORM_ALERT_SLACK_URL is the
// shared fallback for clients without a channel of their own.
const SLACK_WEBHOOK =
  import.meta.env.FORM_SLACK_WEBHOOK || import.meta.env.FORM_ALERT_SLACK_URL;

export const POST: APIRoute = async ({ request }) => {
  try {
    const data   = await request.formData();
    const name    = data.get('name')?.toString().trim()    ?? '';
    const email   = data.get('email')?.toString().trim()   ?? '';
    const message = data.get('message')?.toString().trim() ?? '';
    const subscribe = data.get('subscribe') === 'true';
    const source  = data.get('source')?.toString().trim()  ?? '';

    if (!email || !name || !message) {
      return new Response(JSON.stringify({ error: 'All fields are required.' }), { status: 400 });
    }

    // Internal notification
    let notified = true;
    try {
      await sendWithAlert(
        { client: EMAIL_CONFIG.brand.name, formName: 'Contact form — notification', slackWebhookUrl: SLACK_WEBHOOK },
        () => resend.emails.send({
          from: EMAIL_CONFIG.from.notifications,
          to: EMAIL_CONFIG.notify,
          subject: `New contact form: ${name}`,
          html: `
            <h2>New Contact Form Submission</h2>
            <p><strong>Name:</strong> ${name}</p>
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Message:</strong></p>
            <p>${message.replace(/\n/g, '<br>')}</p>
            <p><strong>Newsletter opt-in:</strong> ${subscribe ? 'Yes' : 'No'}</p>
            ${source ? `<hr><p style="color:#888;font-size:13px"><strong>Source</strong><br>${source.replace(/\n/g, '<br>')}</p>` : ''}
          `,
        })
      );
    } catch (err) {
      notified = false;
      console.error('Resend notify error:', err);
    }

    // Log the submission to the client's Slack channel. It posts even when the
    // email failed — that message is then the only record of the enquiry.
    await notifySubmission({
      client: EMAIL_CONFIG.brand.name,
      slackWebhookUrl: SLACK_WEBHOOK,
      route: 'Contact form',
      formName: `Contact form → ${[EMAIL_CONFIG.notify].flat().join(', ')}`,
      delivered: notified,
      fields: fieldsFromFormData(data),
    });

    // Confirmation to sender
    try {
      await sendWithAlert(
        { client: EMAIL_CONFIG.brand.name, formName: 'Contact form — confirmation', slackWebhookUrl: SLACK_WEBHOOK },
        () => resend.emails.send({
          from: EMAIL_CONFIG.from.confirmations,
          to: email,
          subject: EMAIL_CONFIG.copy.contact.confirmSubject,
          html: EMAIL_CONFIG.copy.contact.confirmBody(name, EMAIL_CONFIG.brand.url),
        })
      );
    } catch (err) {
      console.error('Resend confirm error:', err);
    }

    // Note: contact-form submitters are intentionally NOT added to Mailchimp.
    // Only the proposal form (/api/lead) and the footer newsletter (/api/subscribe)
    // sync to the audience.

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error('Contact API error:', err);
    return new Response(JSON.stringify({ error: 'Something went wrong. Please try again.' }), { status: 500 });
  }
};
