// src/pages/api/contact.ts
// Handles general contact form submissions.
// DO NOT edit this file per client — update src/lib/email.config.ts instead.

import type { APIRoute } from 'astro';
import { Resend } from 'resend';
import { EMAIL_CONFIG } from '~/lib/email.config';
import { sendWithAlert } from '~/lib/form-alert';
import { upsertMailchimpContact } from '~/lib/mailchimp';

const resend = new Resend(import.meta.env.RESEND_API_KEY);
// Astro reads env via import.meta.env, so pass the Slack URL explicitly.
const FORM_ALERT_SLACK_URL = import.meta.env.FORM_ALERT_SLACK_URL;

export const POST: APIRoute = async ({ request }) => {
  try {
    const data   = await request.formData();
    const name    = data.get('name')?.toString().trim()    ?? '';
    const email   = data.get('email')?.toString().trim()   ?? '';
    const message = data.get('message')?.toString().trim() ?? '';
    const subscribe = data.get('subscribe') === 'true';
    const source  = data.get('source')?.toString().trim()  ?? '';

    if (!email || !name || !message) {
      return new Response(JSON.stringify({ error: 'All fields are required.' }), { status: 400 });
    }

    // Internal notification
    try {
      await sendWithAlert(
        { client: EMAIL_CONFIG.brand.name, formName: 'Contact form — notification', slackWebhookUrl: FORM_ALERT_SLACK_URL },
        () => resend.emails.send({
          from: EMAIL_CONFIG.from.notifications,
          to: EMAIL_CONFIG.notify,
          subject: `New contact form: ${name}`,
          html: `
            <h2>New Contact Form Submission</h2>
            <p><strong>Name:</strong> ${name}</p>
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Message:</strong></p>
            <p>${message.replace(/\n/g, '<br>')}</p>
            <p><strong>Newsletter opt-in:</strong> ${subscribe ? 'Yes' : 'No'}</p>
            ${source ? `<hr><p style="color:#888;font-size:13px"><strong>Source</strong><br>${source.replace(/\n/g, '<br>')}</p>` : ''}
          `,
        })
      );
    } catch (err) {
      console.error('Resend notify error:', err);
    }

    // Confirmation to sender
    try {
      await sendWithAlert(
        { client: EMAIL_CONFIG.brand.name, formName: 'Contact form — confirmation', slackWebhookUrl: FORM_ALERT_SLACK_URL },
        () => resend.emails.send({
          from: EMAIL_CONFIG.from.confirmations,
          to: email,
          subject: EMAIL_CONFIG.copy.contact.confirmSubject,
          html: EMAIL_CONFIG.copy.contact.confirmBody(name, EMAIL_CONFIG.brand.url),
        })
      );
    } catch (err) {
      console.error('Resend confirm error:', err);
    }

    // Add / update the contact in Mailchimp on every submission (upsert).
    await upsertMailchimpContact({
      email,
      firstName: name.split(' ')[0],
      lastName:  name.split(' ').slice(1).join(' '),
      tags: EMAIL_CONFIG.mailchimp.defaultTags,
    });

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error('Contact API error:', err);
    return new Response(JSON.stringify({ error: 'Something went wrong. Please try again.' }), { status: 500 });
  }
};
