// src/pages/api/lead.ts
// Handles primary lead/inquiry form submissions, routed per `intent`.
// DO NOT edit this file per client — update src/lib/email.config.ts instead.

import type { APIRoute } from 'astro';
import { Resend } from 'resend';
import mailchimp from '@mailchimp/mailchimp_marketing';
import { EMAIL_CONFIG } from '~/lib/email.config';
import { sendWithAlert } from '~/lib/form-alert';
import { addToPipedrive } from '~/lib/pipedrive';

const resend = new Resend(import.meta.env.RESEND_API_KEY);
// Astro reads env via import.meta.env, so pass the Slack URL explicitly.
const FORM_ALERT_SLACK_URL = import.meta.env.FORM_ALERT_SLACK_URL;

if (EMAIL_CONFIG.mailchimp.enabled) {
  mailchimp.setConfig({
    apiKey: import.meta.env.MAILCHIMP_API_KEY,
    server: import.meta.env.MAILCHIMP_SERVER_PREFIX,
  });
}

export const POST: APIRoute = async ({ request }) => {
  try {
    const data     = await request.formData();
    const honeypot = data.get('website')?.toString() ?? '';
    if (honeypot) {
      // Bot filled the honeypot field — silently discard
      return new Response(JSON.stringify({ success: true }), { status: 200 });
    }
    const name    = data.get('name')?.toString().trim()    ?? '';
    const email   = data.get('email')?.toString().trim()   ?? '';
    const phone   = data.get('phone')?.toString().trim()   ?? '';
    const company = data.get('company')?.toString().trim() ?? '';
    const source  = data.get('source')?.toString().trim()  ?? '';
    const intent  = data.get('intent')?.toString().trim()  ?? '';
    const ref     = data.get('ref')?.toString().trim()     ?? '';
    const message = data.get('message')?.toString().trim() ?? '';
    // stage: 'partial' = multi-step form's contact step was completed but the form
    // isn't finished yet (capture the lead now); 'complete' (default) = full submit.
    const stage     = data.get('stage')?.toString().trim() ?? 'complete';
    const isPartial = stage === 'partial';

    if (!email || !name) {
      return new Response(JSON.stringify({ error: 'Name and email are required.' }), { status: 400 });
    }

    // Route the notification to the right inbox by intent (falls back to default).
    const notifyTo = EMAIL_CONFIG.routes[intent] ?? EMAIL_CONFIG.notify;
    // Visible CC, per intent (vendor/general skip Jeff — see email.config.ts).
    const notifyCc = EMAIL_CONFIG.notifyCcByIntent[intent] ?? EMAIL_CONFIG.notifyCc;

    // An intent with an explicitly empty route (e.g. `rental`, pending the client's
    // destination inbox) is accepted but intentionally NOT delivered anywhere yet —
    // no staff email, no confirmation, no Mailchimp. Set a recipient in email.config.ts
    // routes to activate it.
    if (!notifyTo.length) {
      return new Response(JSON.stringify({ success: true }), { status: 200 });
    }

    // Per-intent content (subject + submitter confirmation) — see email.config.ts.
    const intentCfg = EMAIL_CONFIG.intents[intent] ?? EMAIL_CONFIG.intents.default;

    // Structured per-intent answers, sent by the form as a labeled list. Render
    // EVERY field with its real label.
    const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    let detailFields: { label: string; value: string }[] = [];
    try {
      const parsed = JSON.parse(data.get('fieldsJson')?.toString() ?? '[]');
      if (Array.isArray(parsed)) {
        detailFields = parsed
          .filter((f) => f && typeof f.label === 'string')
          .map((f) => ({ label: String(f.label), value: String(f.value ?? '').trim() }));
      }
    } catch { /* ignore malformed fieldsJson */ }
    const detailRows = detailFields
      .map((f) =>
        `<tr><td style="padding:4px 14px 4px 0;color:#888;white-space:nowrap;vertical-align:top"><strong>${esc(f.label)}</strong></td><td style="padding:4px 0">${f.value ? esc(f.value) : '—'}</td></tr>`)
      .join('');

    // Internal notification — alerts Slack + email if the send fails (then re-throws → 500).
    // Partial leads get a distinct subject + banner so staff can chase abandoned forms.
    await sendWithAlert(
      {
        client: EMAIL_CONFIG.brand.name,
        formName: `${intentCfg.label}${intent ? ` (${intent})` : ''}${isPartial ? ' — partial' : ''}`,
        slackWebhookUrl: FORM_ALERT_SLACK_URL,
        alertEmail: { apiKey: import.meta.env.RESEND_API_KEY, to: EMAIL_CONFIG.alertsTo, from: EMAIL_CONFIG.from.notifications },
      },
      () => resend.emails.send({
        from:    EMAIL_CONFIG.from.notifications,
        replyTo: EMAIL_CONFIG.replyTo,
        to:      notifyTo,
        ...(notifyCc.length ? { cc: notifyCc } : {}),
        subject: isPartial ? `Started (incomplete): ${intentCfg.label} — ${company || name}` : intentCfg.notifySubject(company || name),
        html: `
          ${isPartial ? `<p style="background:#FFF4E5;border-left:3px solid #E0902F;padding:10px 14px;margin:0 0 14px;font-size:14px;color:#7a5310"><strong>⚠️ Started but not yet submitted.</strong> This person completed the contact step of the proposal form. Reach out — they may not finish on their own.</p>` : ''}
          <h2>${esc(intentCfg.label)}${isPartial ? ' (incomplete)' : ''}</h2>
          <p><strong>Name:</strong> ${esc(name)}</p>
          <p><strong>Email:</strong> ${esc(email)}</p>
          ${phone   ? `<p><strong>Phone:</strong> ${esc(phone)}</p>` : ''}
          ${company ? `<p><strong>Company:</strong> ${esc(company)}</p>` : ''}
          ${detailRows ? `<table style="border-collapse:collapse;margin:14px 0;font-size:14px">${detailRows}</table>` : ''}
          ${message ? `<p><strong>Message:</strong><br>${esc(message).replace(/\n/g, '<br>')}</p>` : ''}
          <hr><p style="color:#888;font-size:12px">${ref ? `Ref ${esc(ref)} · ` : ''}Form: ${esc(intent || 'lead')}${isPartial ? ' · stage: partial' : ''}${source ? ` · Source ${esc(source)}` : ''}</p>
        `,
      })
    );

    // Confirmation to submitter — only on a COMPLETE submit (don't confirm a half-finished form).
    if (!isPartial) {
      const firstName = name.split(' ')[0] || name;
      // Recap of what they submitted, so the sender can see their own answers.
      const summaryBlock = (detailRows || message)
        ? `<hr style="border:none;border-top:1px solid #e5e5ef;margin:22px 0">
           <p style="font-size:13px;color:#888;margin:0 0 8px"><strong>What you shared with us</strong></p>
           ${detailRows ? `<table style="border-collapse:collapse;font-size:14px">${detailRows}</table>` : ''}
           ${message ? `<p style="font-size:14px;margin:12px 0 0"><strong>In your words:</strong><br>${esc(message).replace(/\n/g, '<br>')}</p>` : ''}`
        : '';
      const { error: confirmError } = await resend.emails.send({
        from:    EMAIL_CONFIG.from.hello,
        replyTo: EMAIL_CONFIG.replyTo,
        to:      email,
        ...(EMAIL_CONFIG.bcc.length ? { bcc: EMAIL_CONFIG.bcc } : {}),
        subject: intentCfg.confirmSubject,
        html:    intentCfg.confirmBody(firstName, EMAIL_CONFIG.brand.url) + summaryBlock,
      });
      if (confirmError) console.error('Resend confirm error:', confirmError);
    }

    // Optional Mailchimp — adds leads to the list when enabled
    if (EMAIL_CONFIG.mailchimp.enabled) {
      try {
        await mailchimp.lists.addListMember(import.meta.env.MAILCHIMP_AUDIENCE_ID ?? import.meta.env.MAILCHIMP_LIST_ID, {
          email_address: email,
          status: 'subscribed',
          merge_fields: {
            FNAME:   name.split(' ')[0],
            LNAME:   name.split(' ').slice(1).join(' '),
            COMPANY: company,
          },
          tags: isPartial
            ? [...EMAIL_CONFIG.mailchimp.defaultTags, 'proposal-incomplete']
            : EMAIL_CONFIG.mailchimp.defaultTags,
        });
      } catch (err: any) {
        console.error('Mailchimp lead error:', err?.response?.body ?? err);
      }
    }

    // Push COMPLETE PROPOSAL submissions into Pipedrive (Organization + Person + Deal).
    // Proposals only — vendor bids / general questions / rentals are not sales
    // deals, so they don't create Pipedrive records. No-op on stg/dev or until
    // PIPEDRIVE_API_TOKEN is set; never throws. Partials are skipped too.
    if (!isPartial && intent === 'proposal') {
      const role = detailFields.find((f) => /role/i.test(f.label))?.value || '';
      const notesText = [
        ...detailFields.map((f) => `${f.label}: ${f.value || '—'}`),
        message ? `\nMessage:\n${message}` : '',
      ].filter(Boolean).join('\n');
      await addToPipedrive({
        email, name, phone, role, org: company,
        notes: notesText,
        source: `${intentCfg.label}${ref ? ` · ${ref}` : ''}`,
      });
    }

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error('Lead API error:', err);
    return new Response(JSON.stringify({ error: 'Something went wrong. Please try again.' }), { status: 500 });
  }
};
