// src/pages/api/subscribe.ts
// Handles newsletter/email list opt-ins (email only, name optional).
// DO NOT edit this file per client — update src/lib/email.config.ts instead.

import type { APIRoute } from 'astro';
import { EMAIL_CONFIG } from '~/lib/email.config';
import { upsertMailchimpContact } from '~/lib/mailchimp';

export const POST: APIRoute = async ({ request }) => {
  try {
    const data      = await request.formData();
    const honeypot  = data.get('website')?.toString() ?? '';
    if (honeypot) {
      // Bot filled the hidden honeypot field — silently discard (mirrors /api/lead).
      return new Response(JSON.stringify({ success: true }), { status: 200 });
    }
    const email     = data.get('email')?.toString().trim()     ?? '';
    const firstName = data.get('firstName')?.toString().trim() ?? '';

    if (!email) {
      return new Response(JSON.stringify({ error: 'Email is required.' }), { status: 400 });
    }

    // Add / update the subscriber in Mailchimp (upsert) + apply the newsletter
    // tag. `doubleOptIn` creates NEW members as 'pending' so Mailchimp sends its
    // confirmation email — the subscriber only joins the list after clicking it.
    // This is our spam gate: bots can't confirm, so they never land on the list.
    // A returning subscriber is refreshed rather than erroring out.
    await upsertMailchimpContact({
      email,
      firstName,
      tags: EMAIL_CONFIG.mailchimp.subscribeTags ?? EMAIL_CONFIG.mailchimp.defaultTags,
      doubleOptIn: true,
    });

    // No welcome email is sent from here: Mailchimp owns the newsletter opt-in
    // lifecycle now (confirmation email → optional final welcome). Sending our
    // own "you're on the list" note would be premature — they haven't confirmed.

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error('Subscribe API error:', err);
    return new Response(JSON.stringify({ error: 'Something went wrong. Please try again.' }), { status: 500 });
  }
};
